### ISSUE TITLE
login failed NeedToken (own wiki)

### ISSUE THREAD

**Issue by tomsgithub** [ritschwumm/commonist#11]
Since wikimedia 1.27 login fails in a own wiki
"UploadFilesTask.scala:96 login failed NeedToken"
commonist-1.8.0, Java 8.151, MediaWiki 1.27.4, PHP 5.5.9-1ubuntu4.22, PostgreSQL 9.4.15
Is there any chance to fix it?
More details needed?
Thanks a lot.

**Comment by ritschwumm** [comment]
i'll give it a try, if i can reproduce the issue it's probably easy to fix

**Comment by ritschwumm** [comment]
hm - at least on commons.wikimedia.org everything seems to work.
which version do you use, and you paste the commonist's log from after you pressed the login button?
maybe there is something interesting to see there.

**Comment by tomsgithub** [comment]
Hi, thanks a lot!
versions: commonist-1.8.0, Java 8.151, MediaWiki 1.27.4, PHP 5.5.9-1ubuntu4.22, PostgreSQL 9.4.15
With mediawiki 1.26 it worked.

INFO    [2018-01-05T09:26:40.890Z]      UploadFilesTask.scala:85        logging in
DEBUG   [2018-01-05T09:26:40.922Z]      Connection.scala:119    POST https://einbandforschung.gbv.de/api.php HTTP/1.1
DEBUG   [2018-01-05T09:26:41.341Z]      Connection.scala:122    HTTP/1.1 200 OK
DEBUG   [2018-01-05T09:26:41.376Z]      Connection.scala:119    POST https://einbandforschung.gbv.de/api.php HTTP/1.1
DEBUG   [2018-01-05T09:26:41.446Z]      Connection.scala:122    HTTP/1.1 200 OK
INFO    [2018-01-05T09:26:41.459Z]      UploadFilesTask.scala:96        login failed    NeedToken

**Comment by ritschwumm** [comment]
hm, that's not much :(
any idea whether it's your wiki behaving differently than mediawiki or the commonist doing something different when talking to your wiki vs. talking to commons?

**Comment by tomsgithub** [comment]
Thank you. That was exactly the right question. There was a problem with SqlBagOStuff.php (PostgreSQL):
Requests from Commonist were blocked. "PHP Notice:  Uncommitted DB writes (transaction from DatabaseBase::query (LCStoreDB::get))" - Mediawiki has resolved the issue with version 1.29.
Thanks a lot for Commonist. Great program.
