### ISSUE TITLE
Website djini.de is down

### ISSUE THREAD

**Issue by putnik** [ritschwumm/commonist#22]
There is no possibility to get binary files.

**Comment by ritschwumm** [comment]
works for me right now - do you still see this?

**Comment by putnik** [comment]
Yes, there is still an connection error. The issue is confirmed by several users from Russia.

**Comment by ritschwumm** [comment]
sounds like some filter mechanism is preverting you - the server looks fine to me :/

**Comment by putnik** [comment]
Sorry, it turned out that the problem is not on your side. Subnet 178.63.0.0/16 is blocked in Russia by Roskomnadzor.
