### ISSUE TITLE
Extract heading (=Direction of image) from Exif/metadata and add it to location template

### ISSUE THREAD

**Issue by Aschroet** [ritschwumm/commonist#6]
Analogous to https://phabricator.wikimedia.org/T39925 it would be nice if the _commonist_ would also include the heading into the location template if available in Exif.

**Comment by ritschwumm** [comment]
do you have a test image for me where this field is set?

**Comment by Aschroet** [comment]
Of course. Here you are. ![dsc05556](https://cloud.githubusercontent.com/assets/19612739/15663256/43a5b9d2-26f9-11e6-9bd9-cb60259a06fd.JPG)

**Comment by ritschwumm** [comment]
cool, i can get the heading from this. have to think a bit about the gui, though.

**Comment by ritschwumm** [comment]
implementation is finished and seems to be working - i'll test and upload soon(ish).
