### ISSUE TITLE
Hochladen von fehlgeschlagen (Sourced file: jar:http://neonstau.de/commonist/wa/commonist-1.6.1.jar!/image_wikimedia_commons.bpp unknown error: access denied ("java.lang.RuntimePermission" "accesDeclaredMembers"))

### ISSUE THREAD

**Issue by Jarabo** [ritschwumm/commonist#8]
Hello,
I tried to upload some pictures with Commonist. I launched it via Web Start, filled out the forms and chosed some pictures. Then I pressed the Hochladen-Button and I received the error message:

_Hochladen von fehlgeschlagen (Sourced file: jar:http://neonstau.de/commonist/wa/commonist-1.6.1.jar!/image_wikimedia_commons.bpp unknown error: access denied ("java.lang.RuntimePermission" "accesDeclaredMembers"))_

How can I fix this?

**Comment by ritschwumm** [comment]
good question. which java version and which operating system are you using?

**Comment by Jarabo** [comment]
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

and

Ubuntu 16.04.2 LTS 64-Bit

**Comment by Jarabo** [comment]
Just-released 1.7.0? What do you mean with that?

**Comment by Aschroet** [comment]
That there is a new commonist version available.

**Comment by Jarabo** [comment]
Still not working. Same error message now with 1.7.0.

**Comment by ritschwumm** [comment]
interesting: oracle jdk 1.8.0_121 on ubuntu is working for me.
so - why is openjdk behaving differently?

**Comment by Jarabo** [comment]
With the jar file it works. Thank you. So it seems its a problem with the webstart? Are you gonna trying to fix this? 

Best regards

**Comment by ritschwumm** [comment]
i'll try to install openJDK and see whether i can reproduce it that way -
personally i don't use webstart much any more since apple more or less killed it on osx.

**Comment by Aschroet** [comment]
It would be valuable when on the website there are also elder versions 
of the Commonist available. For me the latest does not work because if 
still use Java 1.7.

**Comment by ritschwumm** [comment]
@Aschroet sorry, no. java 7 is dead and buried. really, do yourself a favor and upgrade.

**Comment by frindsbury** [comment]
Sounds like an excellent idea- but it is not available in Mint 17.3 or 
other Ubuntu repositories yet. That usually means there are integration 
issues that are not yet solved.

But before I risk all can you tell me- will 1.8.0 be able to pull my GPS 
location from out of the images exif?

**Comment by ritschwumm** [comment]
@Aschroet @frindsbury i think this issue is the wrong place to discuss which java version to use for the commonist, let's move that elsewhere.
