### ISSUE TITLE
Use native system style on Windows, Mac and Linux

### ISSUE THREAD

**Issue by theel0ja** [ritschwumm/commonist#9]
https://docs.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html

**Comment by ritschwumm** [comment]
why?

**Comment by theel0ja** [comment]
@ritschwumm The application isn't integrating to system's theme.

**Comment by ritschwumm** [comment]
sorry, but i don't care enough about the looks to invest time in this.
